<a href="https://colab.research.google.com/github/vigneshK0404/NOva_Fitter_CNF/blob/main/CNF_Modified.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install torchinfo
!pip install nflows

In [2]:
import torch
import torchinfo
import numpy as np
import sklearn
import matplotlib.pyplot as plt
import tqdm
from torch.utils.data import DataLoader
import time

In [3]:
from nflows.flows.base import Flow  # a container for full Flow
from nflows.distributions.normal import StandardNormal  # Gaussian latent space distribution
from nflows.transforms.base import (
    CompositeTransform,
)  # a wrapper to stack simpler transformations to form a more complex one
from nflows.transforms.autoregressive import (
    MaskedAffineAutoregressiveTransform,
)  # the basic transformation, which we will stack several times
from nflows.transforms.autoregressive import (
    MaskedPiecewiseRationalQuadraticAutoregressiveTransform,
)  # the basic transformation, which we will stack several times
from nflows.transforms.permutations import ReversePermutation # a layer that simply reverts the order of outputs

In [4]:
print(torch.cuda.is_available())
print(torch.cuda.device_count())
dnumber = 0
device = torch.device(f"cuda:{dnumber}" if torch.cuda.is_available() else "cpu")
print(device)
device_name = torch.cuda.get_device_name(dnumber)
print(device_name)

True
1
cuda:0
NVIDIA A100-SXM4-80GB


In [23]:
def gauss(N,mu,sig,x):
    N_t = N.reshape(-1,1)
    mu_t = mu.reshape(-1,1)
    sig_t = sig.reshape(-1,1)

    term1 = N_t / (sig_t * np.sqrt(2 * np.pi))
    term2 = np.exp(-0.5 * np.square((x - mu_t) / sig_t))
    return np.array(term1 * term2)


def generatePrior(sampleSize):
    N1 = np.random.uniform(10,50,sampleSize)
    N2 = np.random.uniform(10,30,sampleSize)

    mu1 = np.random.uniform(1,3,sampleSize)
    mu2 = np.random.uniform(5,9,sampleSize)

    sig1 = np.random.uniform(1,3,sampleSize)
    sig2 = np.random.uniform(5,9,sampleSize)

    return N1,mu1,sig1,N2,mu2,sig2


def generateTrainingData(uniqueSampleNum, sampleNumber):

  N1,mu1,sig1,N2,mu2,sig2 = generatePrior(uniqueSampleNum)

  raw = np.arange(0.5,10,1) #startbinCenter, endBinEdge, StepSize [0.5,1.5...9.5]
  gaussTotal = gauss(N1,mu1,sig1,raw) + gauss(N2,mu2,sig2,raw)
  thetaData = np.column_stack((N1,mu1,sig1,N2,mu2,sig2))

  fullGaussMatrix = np.repeat(gaussTotal,repeats=sampleNumber,axis=0)
  dataPoisson = np.random.poisson(lam=fullGaussMatrix,size=None).reshape(-1,1)

  thetaExtend_len = len(raw)

  fullthetaData = np.repeat(thetaData,repeats=sampleNumber*thetaExtend_len,axis=0)

  return dataPoisson, fullthetaData

dataPoisson, thetaData = generateTrainingData(2,1)

print(thetaData)
print(dataPoisson)


[[32.83678867  1.01183497  1.1423718  22.47759909  6.38165238  6.38095182]
 [32.83678867  1.01183497  1.1423718  22.47759909  6.38165238  6.38095182]
 [32.83678867  1.01183497  1.1423718  22.47759909  6.38165238  6.38095182]
 [32.83678867  1.01183497  1.1423718  22.47759909  6.38165238  6.38095182]
 [32.83678867  1.01183497  1.1423718  22.47759909  6.38165238  6.38095182]
 [32.83678867  1.01183497  1.1423718  22.47759909  6.38165238  6.38095182]
 [32.83678867  1.01183497  1.1423718  22.47759909  6.38165238  6.38095182]
 [32.83678867  1.01183497  1.1423718  22.47759909  6.38165238  6.38095182]
 [32.83678867  1.01183497  1.1423718  22.47759909  6.38165238  6.38095182]
 [32.83678867  1.01183497  1.1423718  22.47759909  6.38165238  6.38095182]
 [11.57838143  1.04847821  1.3638702  10.45193323  7.94432419  5.01185182]
 [11.57838143  1.04847821  1.3638702  10.45193323  7.94432419  5.01185182]
 [11.57838143  1.04847821  1.3638702  10.45193323  7.94432419  5.01185182]
 [11.57838143  1.04847821